apiVersion: apps/v1
kind: Deployment
metadata:
  name: akmebank-ui
  namespace: thinkdemo
  labels:
    app.kubernetes.io/part-of: akmebank
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: akmebank-ui-selector
  template:
    metadata:
      labels:
        app: akmebank-ui-selector
    spec:
      containers:
      - name: sample-container
        image: SAMPLE_IMAGE_AND_TAG
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
           limits:
             memory: 512Mi
             cpu: 500m
           requests:
             memory: 64Mi
             cpu: 50m

